# This file was generated by GoReleaser. DO NOT EDIT.
cask "cu" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ad771fe33ed5967a23e3b2fff04bfbff2d99f17b0a986aa579bda541c54a7c16"
      url "https://github.com/timimsms/cu/releases/download/v#{version}/cu_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "13d602da8563f26e0c71e38808494d156ad26545852904cf86f033814c56898c"
      url "https://github.com/timimsms/cu/releases/download/v#{version}/cu_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2550b3b392bb394a60b6b4ae04b8027c712f199e27bccbb20146828274b5206"
      url "https://github.com/timimsms/cu/releases/download/v#{version}/cu_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "04907f4764357ad4c55ff1df8d6783f7ba9dd060603aea3ea5ea2d1a310f3f84"
      url "https://github.com/timimsms/cu/releases/download/v#{version}/cu_Linux_arm64.tar.gz"
    end
  end

  name "cu"
  desc "A CLI for ClickUp — like gh is for GitHub"
  homepage "https://github.com/timimsms/cu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cu"]
    end
  end

  # No zap stanza required

end
